# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"

stages:
  - initial
  - second

build_release_x64:
  tags:
    - windows, shell
  stage: initial
  script:
    - 7z x -y -ohdf5 hdf5_package\CMake-hdf5-1.10.6\hdf5_x64_release.zip *
    - md build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64 ..\src
    - cmake --build . --config Release --target install
  artifacts:
    paths:
      - output/win/x64

build_release_x86:
  tags:
    - windows, shell
  stage: initial
  script:
    - 7z x -y -ohdf5 hdf5_package\CMake-hdf5-1.10.6\hdf5_x86_release.zip *
    - md build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A Win32 ..\src
    - cmake --build . --config Release --target install
  artifacts:
    paths:
      - output/win/x86

testing_x64:
  tags:
    - docker, debian
  stage: second
  needs: ["build_release_x64"]
  variables:
    IGORPRO_TAG: "v8"
    IGORPRO_VERSION: "8"
  image:
    name: ${CI_REGISTRY}/internal/docker-igorpro:${IGORPRO_TAG}
  script:
    - 7z x -y -ohdf5 hdf5_package/CMake-hdf5-1.10.6/hdf5_x64_release.zip *
    - ln -rs utf/procedures "/home/igor/WaveMetrics/Igor Pro ${IGORPRO_VERSION} User Files/User Procedures/utf"
    - ln -rs output/win/x64/*.xop "/home/igor/WaveMetrics/Igor Pro ${IGORPRO_VERSION} User Files/Igor Extensions (64-bit)/"
    - ln -rs hdf5/HDF5-1.10.6-win64/bin/*.dll "/home/igor/WaveMetrics/Igor Pro ${IGORPRO_VERSION} User Files/Igor Extensions (64-bit)/"
    - ln -rs additional_dlls/x64/*.dll "/home/igor/WaveMetrics/Igor Pro ${IGORPRO_VERSION} User Files/Igor Extensions (64-bit)/"
    - touch tests/DO_AUTORUN.TXT
    - igorpro execute --screenshot "tests/Experiment.pxp"
    - exit $(grep "errors\|failures=\"[0-9]\+\"" tests/JU_*.xml | grep -cv "failures=\"0\" errors=\"0\"")
  artifacts:
    when: always
    reports:
      junit: tests/JU_*.xml
    paths:
      - tests/*.xml
      - screenshot/*.png
  retry:
    max: 2
    when: runner_system_failure
  dependencies:
    - build_release_x64

testing_x86:
  tags:
    - docker, debian
  stage: second
  needs: ["build_release_x86"]
  variables:
    IGORPRO_TAG: "v8"
    IGORPRO_VERSION: "8"
  image:
    name: ${CI_REGISTRY}/internal/docker-igorpro:${IGORPRO_TAG}
  script:
    - 7z x -y -ohdf5 hdf5_package/CMake-hdf5-1.10.6/hdf5_x86_release.zip *
    - ln -rs utf/procedures "/home/igor/WaveMetrics/Igor Pro ${IGORPRO_VERSION} User Files/User Procedures/utf"
    - ln -rs output/win/x86/*.xop "/home/igor/WaveMetrics/Igor Pro ${IGORPRO_VERSION} User Files/Igor Extensions/"
    - ln -rs hdf5/HDF5-1.10.6-win32/bin/*.dll "/home/igor/WaveMetrics/Igor Pro ${IGORPRO_VERSION} User Files/Igor Extensions/"
    - ln -rs additional_dlls/x86/*.dll "/home/igor/WaveMetrics/Igor Pro ${IGORPRO_VERSION} User Files/Igor Extensions/"
    - touch tests/DO_AUTORUN.TXT
    - igorpro execute --32bit --screenshot "tests/Experiment.pxp"
    - exit $(grep "errors\|failures=\"[0-9]\+\"" tests/JU_*.xml | grep -cv "failures=\"0\" errors=\"0\"")
  artifacts:
    when: always
    reports:
      junit: tests/JU_*.xml
    paths:
      - tests/*.xml
      - screenshot/*.png
  retry:
    max: 2
    when: runner_system_failure
  dependencies:
    - build_release_x86
